apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://partio-prometheus:9090
    isDefault: true
    jsonData:
      httpMethod: POST
    editable: false

  - name: Tempo
    uid: tempo
    type: tempo
    access: proxy
    url: http://partio-tempo:3200
    jsonData:
      tracesToLogsV2:
        datasourceUid: loki
        filterByTraceID: true
      serviceMap:
        datasourceUid: prometheus
      nodeGraph:
        enabled: true
    editable: false

  - name: Loki
    uid: loki
    type: loki
    access: proxy
    url: http://partio-loki:3100
    editable: false
