<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>partio-mcp</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\sdk\csharp\Partio.Sdk\Partio.Sdk.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Voltaic" Version="0.7.1" />
    <PackageReference Include="SyslogLogging" Version="*" />
    <PackageReference Include="SerializationHelper" Version="*" />
  </ItemGroup>

</Project>
